import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { TextInput } from "../components";

export default function Home() {
	const [nameError, setNameError] = useState(false);
	const [emailError, setEmailError] = useState(false);

	const validateEmail = email => {
		return String(email)
			.toLowerCase()
			.match(
				/^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
			);
	};
	const validateName = email => {
		return /^[A-Za-z ]+$/.test(email);
	};

	const nameChange = event => {
		console.log("name:", event.target.value);
		if (!validateName(event.target.value)) {
			setNameError(true);
		} else {
			setNameError(false);
		}
	};

	const emailChange = event => {
		console.log("email: ", event.target.value);
		if (!validateEmail(event.target.value)) {
			setEmailError(true);
		} else {
			setEmailError(false);
		}
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				{/* This is just to text my components */}
				<TextInput type="name" inputChange={nameChange} error={nameError} />
				<TextInput type="email" inputChange={emailChange} error={emailError} />
			</main>

			<footer className={styles.footer}></footer>
		</div>
	);
}
