import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { TextInput } from "../components";

export default function Home() {
	const nameChange = event => {
		console.log("name:", event.target.value);
	};

	const emailChange = event => {
		console.log("email: ", event.target.value);
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				{/* This is just to text my components */}
				<TextInput type="name" inputChange={nameChange} />
				<TextInput type="email" inputChange={emailChange} />
			</main>

			<footer className={styles.footer}></footer>
		</div>
	);
}
